name: CD

on:
  push:
    paths-ignore:
      - "docs/**"
      - "*.md"

jobs:
  package:
    env:
      DisableGitVersionTask: true
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 9.0.x
   
