name: CI

on:
  push:
    paths-ignore:
      - "docs/**"
      - "*.md"
  pull_request:
    paths-ignore:
      - "docs/**"
      - "*.md"

jobs:
  test:
    env:
      DisableGitVersionTask: true
    strategy:
      matrix:
        include:
          - os: windows-latest
            build_config: Debug
          - os: ubuntu-latest
            build_config: Linux-Debug
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore
      run: dotnet restore 
    - name: Test
      run: dotnet test 
